import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

export type RFQReferenceFile = {
  filename: string;
  originalName: string;
  type: string;
  size: number;
};

export type RFQRecord = {
  id: string;
  createdAt: string;
  ipAddress: string;
  name: string;
  company: string;
  country: string;
  email: string;
  whatsapp: string;
  product: string;
  quantity: string;
  customLogo: string;
  customPackaging: string;
  targetPrice: string;
  requirements: string;
  intent: string;
  referenceImage?: RFQReferenceFile;
};

async function ensureDataPaths() {
  const dataFile = path.join(
    /* turbopackIgnore: true */ process.cwd(),
    "data",
    "rfq-submissions.json",
  );
  const uploadDir = path.join(
    /* turbopackIgnore: true */ process.cwd(),
    "data",
    "rfq-uploads",
  );
  await mkdir(uploadDir, { recursive: true });
  return {
    dataFile,
    uploadDir,
  };
}

export async function saveRFQRecord(record: RFQRecord) {
  const { dataFile } = await ensureDataPaths();
  let existing: RFQRecord[] = [];

  if (existsSync(dataFile)) {
    try {
      existing = JSON.parse(await readFile(dataFile, "utf8")) as RFQRecord[];
    } catch {
      existing = [];
    }
  }

  existing.unshift(record);
  await writeFile(dataFile, `${JSON.stringify(existing, null, 2)}\n`, "utf8");
}

export async function saveRFQReferenceFile({
  file,
  filename,
}: {
  file: File;
  filename: string;
}) {
  const { uploadDir } = await ensureDataPaths();
  const filepath = path.join(uploadDir, filename);
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(filepath, buffer);
}

export async function readRFQReferenceFile(filename: string) {
  const { uploadDir } = await ensureDataPaths();
  // `filename` is generated by server-side validation, never a client path.
  return readFile(path.join(uploadDir, filename));
}
