"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { neon } from "@neondatabase/serverless";
import { requireAdmin } from "@/lib/auth/require-admin";
import { slugify } from "@/lib/admin/products";
const db=()=>neon(process.env.DATABASE_URL!); const text=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>Math.max(0,Number(text(f,k)||0));
const json=(f:FormData,k:string)=>{const v=text(f,k);if(!v)return k==="specifications"?{}:[];try{return JSON.parse(v)}catch{throw new Error(`${k} must be valid JSON.`)}};
export async function saveCategory(form:FormData){await requireAdmin();const id=text(form,"id"),name=text(form,"name"),slug=slugify(text(form,"slug")||name);if(!name||!slug)throw new Error("Name and slug are required.");try{if(id)await db().query("UPDATE product_categories SET name=$1,slug=$2,description=$3,sort_order=$4,is_active=$5,updated_at=now() WHERE id=$6",[name,slug,text(form,"description")||null,n(form,"sortOrder"),form.get("isActive")==="on",id]);else await db().query("INSERT INTO product_categories(name,slug,description,sort_order,is_active)VALUES($1,$2,$3,$4,$5)",[name,slug,text(form,"description")||null,n(form,"sortOrder"),form.get("isActive")==="on"])}catch(e){if(String(e).includes("unique"))throw new Error("That category slug already exists.");throw e}revalidatePath("/admin");revalidatePath("/admin/categories");redirect("/admin/categories")}
export async function saveProduct(form:FormData){await requireAdmin();const id=text(form,"id"),name=text(form,"name"),categoryId=text(form,"categoryId"),slug=slugify(text(form,"slug")||name),status=text(form,"status");if(!name||!categoryId||!slug||!["draft","published","archived"].includes(status))throw new Error("Complete the required product fields.");const v=[categoryId,name,slug,text(form,"shortDescription")||null,text(form,"fullDescription")||null,text(form,"moq")||null,text(form,"material")||null,json(form,"specifications"),json(form,"colors"),json(form,"customization"),text(form,"packaging")||null,text(form,"leadTime")||null,form.get("featured")==="on",n(form,"sortOrder"),status,text(form,"seoTitle")||null,text(form,"seoDescription")||null];try{if(id)await db().query("UPDATE products SET category_id=$1,name=$2,slug=$3,short_description=$4,full_description=$5,moq=$6,material=$7,specifications=$8,colors=$9,customization=$10,packaging=$11,lead_time=$12,featured=$13,sort_order=$14,status=$15,seo_title=$16,seo_description=$17,updated_at=now() WHERE id=$18",[...v,id]);else await db().query("INSERT INTO products(category_id,name,slug,short_description,full_description,moq,material,specifications,colors,customization,packaging,lead_time,featured,sort_order,status,seo_title,seo_description)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)",v)}catch(e){if(String(e).includes("products_category_slug_key"))throw new Error("That product slug already exists in this category.");throw e}revalidatePath("/admin");revalidatePath("/admin/products");redirect("/admin/products")}
