"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { neon } from "@neondatabase/serverless";
import { requireAdmin } from "@/lib/auth/require-admin";
import { slugify } from "@/lib/admin/products";
import { deleteProductImage, getProductImages, uploadProductImage, uploadProductMainImage } from "@/lib/products/image-management";
const db=()=>neon(process.env.DATABASE_URL!); const text=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>Math.max(0,Number(text(f,k)||0));
const json=(f:FormData,k:string)=>{const v=text(f,k);if(!v)return k==="specifications"?{}:[];try{return JSON.parse(v)}catch{throw new Error(`${k} must be valid JSON.`)}};
export async function saveCategory(form:FormData){await requireAdmin();const id=text(form,"id"),name=text(form,"name"),slug=slugify(text(form,"slug")||name);if(!name||!slug)throw new Error("Name and slug are required.");try{if(id)await db().query("UPDATE product_categories SET name=$1,slug=$2,description=$3,sort_order=$4,is_active=$5,updated_at=now() WHERE id=$6",[name,slug,text(form,"description")||null,n(form,"sortOrder"),form.get("isActive")==="on",id]);else await db().query("INSERT INTO product_categories(name,slug,description,sort_order,is_active)VALUES($1,$2,$3,$4,$5)",[name,slug,text(form,"description")||null,n(form,"sortOrder"),form.get("isActive")==="on"])}catch(e){if(String(e).includes("unique"))throw new Error("That category slug already exists.");throw e}revalidatePath("/admin");revalidatePath("/admin/categories");redirect("/admin/categories")}
export type ProductSaveState={error:string|null};
export async function saveProduct(_:ProductSaveState,form:FormData):Promise<ProductSaveState>{await requireAdmin();try{const id=text(form,"id"),name=text(form,"name"),categoryId=text(form,"categoryId"),slug=slugify(text(form,"slug")||name),status=text(form,"status");if(!name||!categoryId||!slug||!["draft","published","archived"].includes(status))return {error:"Complete the required product fields."};const v=[categoryId,name,slug,text(form,"shortDescription")||null,text(form,"fullDescription")||null,text(form,"keyFeatures")||null,text(form,"applications")||null,text(form,"certifications")||null,text(form,"moq")||null,text(form,"material")||null,text(form,"sizeSpecs")||null,json(form,"specifications"),json(form,"colors"),json(form,"customization"),text(form,"packaging")||null,text(form,"leadTime")||null,form.get("featured")==="on",n(form,"sortOrder"),status,text(form,"seoTitle")||null,text(form,"seoDescription")||null];if(id)await db().query("UPDATE products SET category_id=$1,name=$2,slug=$3,short_description=$4,full_description=$5,key_features=$6,applications=$7,certifications=$8,moq=$9,material=$10,size_specs=$11,specifications=$12,colors=$13,customization=$14,packaging=$15,lead_time=$16,featured=$17,sort_order=$18,status=$19,seo_title=$20,seo_description=$21,updated_at=now() WHERE id=$22",[...v,id]);else await db().query("INSERT INTO products(category_id,name,slug,short_description,full_description,key_features,applications,certifications,moq,material,size_specs,specifications,colors,customization,packaging,lead_time,featured,sort_order,status,seo_title,seo_description)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)",v);revalidatePath("/admin");revalidatePath("/admin/products");redirect("/admin/products")}catch(e){const code=typeof e==="object"&&e&&"code" in e?(e as {code?:string}).code:"";if(code==="23505"||String(e).includes("products_category_slug_key"))return {error:"A product with this slug already exists in this category."};if(e instanceof Error&&e.message.endsWith("must be valid JSON."))return {error:e.message};throw e}}

export async function saveNewProductWithImages(_:ProductSaveState,form:FormData):Promise<ProductSaveState>{await requireAdmin();try{const name=text(form,"name"),categoryId=text(form,"categoryId"),slug=slugify(text(form,"slug")||name),status=text(form,"status");if(!name||!categoryId||!slug||!["draft","published","archived"].includes(status))return {error:"Complete the required product fields."};const v=[categoryId,name,slug,text(form,"shortDescription")||null,text(form,"fullDescription")||null,text(form,"keyFeatures")||null,text(form,"applications")||null,text(form,"certifications")||null,text(form,"moq")||null,text(form,"material")||null,text(form,"sizeSpecs")||null,json(form,"specifications"),json(form,"colors"),json(form,"customization"),text(form,"packaging")||null,text(form,"leadTime")||null,form.get("featured")==="on",n(form,"sortOrder"),status,text(form,"seoTitle")||null,text(form,"seoDescription")||null];const rows=await db().query("INSERT INTO products(category_id,name,slug,short_description,full_description,key_features,applications,certifications,moq,material,size_specs,specifications,colors,customization,packaging,lead_time,featured,sort_order,status,seo_title,seo_description)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) RETURNING id",v) as Array<{id:string}>;const id=rows[0]?.id;if(!id)throw new Error("Product could not be created.");try{const main=form.get("mainImage");if(main instanceof File&&main.size)await uploadProductMainImage({productId:id,file:main});for(const image of form.getAll("galleryImages")){if(image instanceof File&&image.size)await uploadProductImage({productId:id,file:image,altText:text(form,"galleryImageAlt")||null})}}catch(error){for(const image of await getProductImages(id)){await deleteProductImage(id,image.id).catch(()=>undefined)}await db().query("DELETE FROM products WHERE id=$1",[id]);throw error}revalidatePath("/admin");revalidatePath("/admin/products");redirect(`/admin/products/${id}/edit`)}catch(e){const code=typeof e==="object"&&e&&"code" in e?(e as {code?:string}).code:"";if(code==="23505"||String(e).includes("products_category_slug_key"))return {error:"A product with this slug already exists in this category."};if(e instanceof Error)return {error:e.message.includes("JSON")||e.message.includes("image")||e.message.includes("JPG")||e.message.includes("Product")?e.message:"The product could not be saved. Please try again."};return {error:"The product could not be saved. Please try again."}}}
