import "server-only";
import { neon } from "@neondatabase/serverless";

export type AdminCategory = { id:string; name:string; slug:string; description:string|null; sortOrder:number; isActive:boolean; parentId:string|null; updatedAt:string };
export type AdminProduct = { id:string; name:string; slug:string; categoryId:string; categoryName:string; status:"draft"|"published"|"archived"; featured:boolean; sortOrder:number; updatedAt:string; shortDescription:string|null; fullDescription:string|null; keyFeatures:string|null; applications:string|null; certifications:string|null; moq:string|null; material:string|null; sizeSpecs:string|null; finish:string|null; availableOptions:string|null; wholesaleSupplyDescription:string|null; specifications:Record<string,unknown>; colors:string[]; customization:string[]; packaging:string|null; leadTime:string|null; seoTitle:string|null; seoDescription:string|null; mainImageUrl:string|null };
const db=()=>neon(process.env.DATABASE_URL!);
export const slugify=(value:string)=>value.trim().toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
export async function categories(activeOnly=false){const s=db();return await s.query(`SELECT id,name,slug,description,sort_order AS "sortOrder",is_active AS "isActive",parent_id AS "parentId",updated_at AS "updatedAt" FROM product_categories ${activeOnly?"WHERE is_active=true":""} ORDER BY sort_order,name`) as AdminCategory[]}
export async function category(id:string){return (await db().query(`SELECT id,name,slug,description,sort_order AS "sortOrder",is_active AS "isActive",parent_id AS "parentId",updated_at AS "updatedAt" FROM product_categories WHERE id=$1`,[id]) as AdminCategory[])[0]??null}
export async function products(filters:{status?:string;category?:string}={}){const where:string[]=[];const values:string[]=[];if(filters.status){values.push(filters.status);where.push(`p.status=$${values.length}`)}if(filters.category){values.push(filters.category);where.push(`p.category_id=$${values.length}`)}return await db().query(`SELECT p.id,p.name,p.slug,p.category_id AS "categoryId",c.name AS "categoryName",p.status,p.featured,p.sort_order AS "sortOrder",p.updated_at AS "updatedAt",p.short_description AS "shortDescription",p.full_description AS "fullDescription",p.key_features AS "keyFeatures",p.applications,p.certifications,p.moq,p.material,p.size_specs AS "sizeSpecs",p.finish,p.available_options AS "availableOptions",p.wholesale_supply_description AS "wholesaleSupplyDescription",p.specifications,p.colors,p.customization,p.packaging,p.lead_time AS "leadTime",p.seo_title AS "seoTitle",p.seo_description AS "seoDescription",p.main_image_url AS "mainImageUrl" FROM products p JOIN product_categories c ON c.id=p.category_id ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY p.sort_order,p.updated_at DESC`,values) as AdminProduct[]}
export async function product(id:string){return (await db().query(`SELECT p.id,p.name,p.slug,p.category_id AS "categoryId",c.name AS "categoryName",p.status,p.featured,p.sort_order AS "sortOrder",p.updated_at AS "updatedAt",p.short_description AS "shortDescription",p.full_description AS "fullDescription",p.key_features AS "keyFeatures",p.applications,p.certifications,p.moq,p.material,p.size_specs AS "sizeSpecs",p.finish,p.available_options AS "availableOptions",p.wholesale_supply_description AS "wholesaleSupplyDescription",p.specifications,p.colors,p.customization,p.packaging,p.lead_time AS "leadTime",p.seo_title AS "seoTitle",p.seo_description AS "seoDescription",p.main_image_url AS "mainImageUrl" FROM products p JOIN product_categories c ON c.id=p.category_id WHERE p.id=$1 LIMIT 1`,[id]) as AdminProduct[])[0]??null}
export async function stats(){const r=await db().query("SELECT status,count(*)::int AS count FROM products GROUP BY status");const c=await db().query("SELECT count(*)::int AS count FROM product_categories");return {draft:r.find(x=>x.status==="draft")?.count??0,published:r.find(x=>x.status==="published")?.count??0,archived:r.find(x=>x.status==="archived")?.count??0,categories:c[0]?.count??0}}
