import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter } from "@/components/site-footer";
import { trovaneButton } from "@/components/trovane-button";
import {
  buyerProductGuideSlugs,
  getBuyerProductGuide,
} from "@/lib/blog/buyer-product-guides";
import { petTravelBuyingGuide } from "@/lib/blog/pet-travel-accessories-wholesale";
import { BuyerProductGuidePage } from "./buyer-product-guide-page";

const articleUrl = "https://buildmetriccalc.com/blog/pet-travel-accessories-wholesale-buying-guide";

export const dynamic = "force-static";
export const dynamicParams = false;

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return [petTravelBuyingGuide.slug, ...buyerProductGuideSlugs].map((slug) => ({
    slug,
  }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const slug = (await params).slug;
  const buyerProductGuide = getBuyerProductGuide(slug);
  if (buyerProductGuide) {
    const url = `https://buildmetriccalc.com/blog/${buyerProductGuide.slug}`;
    return {
      title: buyerProductGuide.seoTitle,
      description: buyerProductGuide.description,
      alternates: { canonical: url },
      openGraph: {
        type: "article",
        url,
        title: buyerProductGuide.seoTitle,
        description: buyerProductGuide.description,
        publishedTime: buyerProductGuide.publishedAt,
        images: [
          { url: buyerProductGuide.image, alt: buyerProductGuide.imageAlt },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: buyerProductGuide.seoTitle,
        description: buyerProductGuide.description,
        images: [buyerProductGuide.image],
      },
    };
  }
  if (slug !== petTravelBuyingGuide.slug) return {};
  return {
    title: "Pet Travel Accessories Wholesale: A Buyer’s Guide | TROVANE",
    description: "Source pet travel accessories for wholesale, OEM and private label programs. Compare product types, materials, samples, packaging and supplier capabilities.",
    alternates: { canonical: articleUrl },
    openGraph: { type: "article", url: articleUrl, title: "Pet Travel Accessories Wholesale: A Buyer’s Guide | TROVANE", description: "Source pet travel accessories for wholesale, OEM and private label programs. Compare product types, materials, samples, packaging and supplier capabilities.", publishedTime: petTravelBuyingGuide.publishedAt, images: [{ url: petTravelBuyingGuide.image, alt: petTravelBuyingGuide.imageAlt }] },
    twitter: { card: "summary_large_image", title: "Pet Travel Accessories Wholesale: A Buyer’s Guide | TROVANE", description: "Source pet travel accessories for wholesale, OEM and private label programs. Compare product types, materials, samples, packaging and supplier capabilities.", images: [petTravelBuyingGuide.image] },
  };
}

function ArticleCta() {
  return <aside className="my-14 border-y border-navy/15 bg-mist px-6 py-9 sm:px-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-forest">Discuss your program</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">Ready to turn a buying brief into a quote?</h2><p className="mt-3 max-w-2xl leading-7 text-slate">Tell us the products, target market, quantity and customization direction you are considering. We will review the practical next steps with you.</p><Link className={`mt-6 ${trovaneButton.primary}`} href="/rfq?intent=wholesale-buying-guide&source=pet-travel-accessories-guide">Request a Quote</Link></aside>;
}

export default async function BlogArticlePage({ params }: Props) {
  const slug = (await params).slug;
  const buyerProductGuide = getBuyerProductGuide(slug);
  if (buyerProductGuide) {
    return <BuyerProductGuidePage article={buyerProductGuide} />;
  }
  if (slug !== petTravelBuyingGuide.slug) notFound();
  const structuredData = { "@context": "https://schema.org", "@graph": [
    { "@type": "BlogPosting", headline: petTravelBuyingGuide.title, description: "Source pet travel accessories for wholesale, OEM and private label programs. Compare product types, materials, samples, packaging and supplier capabilities.", mainEntityOfPage: { "@type": "WebPage", "@id": articleUrl }, url: articleUrl, datePublished: petTravelBuyingGuide.publishedAt, dateModified: petTravelBuyingGuide.publishedAt, image: `https://buildmetriccalc.com${petTravelBuyingGuide.image}`, articleSection: petTravelBuyingGuide.category, author: { "@type": "Organization", name: "TROVANE" }, publisher: { "@type": "Organization", name: "TROVANE", logo: { "@type": "ImageObject", url: "https://buildmetriccalc.com/trovane-logo-horizontal-cropped.png" } } },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://buildmetriccalc.com/" }, { "@type": "ListItem", position: 2, name: "Blog", item: "https://buildmetriccalc.com/blog" }, { "@type": "ListItem", position: 3, name: petTravelBuyingGuide.title, item: articleUrl }] },
  ] };

  return <main className="bg-white text-navy"><script dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} type="application/ld+json" />
    <article>
      <header className="border-b border-navy/10 bg-warm px-4 pb-12 pt-8 sm:px-6 sm:pb-16 sm:pt-10 lg:px-8"><div className="mx-auto max-w-[920px]"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-slate"><Link className="transition hover:text-forest" href="/">Home</Link><span aria-hidden="true">/</span><Link className="transition hover:text-forest" href="/blog">Blog</Link><span aria-hidden="true">/</span><span className="text-navy/70">Buyer’s Guide</span></nav><div className="mt-12"><div className="flex flex-wrap items-center gap-x-3 gap-y-2 text-xs font-bold uppercase tracking-[0.16em] text-forest"><span>{petTravelBuyingGuide.category}</span><span aria-hidden="true" className="h-1 w-1 rounded-full bg-forest/60" /><time dateTime={petTravelBuyingGuide.publishedAt}>{petTravelBuyingGuide.publishedLabel}</time></div><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-6xl">{petTravelBuyingGuide.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate">A practical sourcing framework for building a pet travel assortment that works for your customer, channel and operational plan—not simply a list of attractive products.</p></div></div></header>
      <div className="px-4 py-10 sm:px-6 sm:py-14 lg:px-8 lg:py-16"><div className="mx-auto max-w-[780px]"><figure className="relative aspect-[16/8] overflow-hidden bg-mist"><Image alt={petTravelBuyingGuide.imageAlt} className="h-full w-full object-cover" fill priority sizes="(min-width: 1024px) 780px, 100vw" src={petTravelBuyingGuide.image} unoptimized /></figure><div className="mt-12 text-base leading-8 text-slate sm:text-lg">
        <p className="text-xl leading-9 text-navy">Pet travel is a broad category: a customer might be planning a weekend drive, an airline journey, a city commute or a long outdoor trip. For a wholesale buyer, the better question is not “Which items can we buy?” but “Which product set can our customer understand, trust and reorder?” This guide helps retailers and brands convert that question into a workable sourcing brief.</p>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">1. Start with the retail use case, not the supplier catalog</h2><p className="mt-5">Travel products cross several occasions, so a category should start with the intended customer and channel. A compact accessory for a pet boutique will be evaluated differently from a hard-wearing item for a car-accessory retailer. Define the pet size range, transport mode, climate, target price tier and retail channel before comparing samples.</p><p className="mt-5">A useful first assortment often combines containment, restraint, comfort, feeding and cleaning. Browse the <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/products/travel-car">Travel &amp; Car collection</Link> as a starting point, then narrow the brief to the items that solve a recognisable journey for your buyer.</p><h3 className="mt-9 text-2xl font-semibold tracking-tight text-navy">Write a one-page brief</h3><p className="mt-4">Include your buyer type, destination market, sales channel, launch window, target pet size, product priorities and required branding. This gives a supplier context for discussing material choices, packing and a realistic sample route without assuming a universal MOQ or lead time.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">2. Build the assortment around travel moments</h2><p className="mt-5">A well-planned range makes adjacent items easy to understand. For example, a carrier or backpack supports transport; a restraint supports in-car use; a litter solution supports longer journeys; and a feeding accessory supports stops along the way. This creates a clearer merchandising story than mixing unrelated pet goods under a generic travel label.</p><ul className="mt-6 space-y-3 border-l-2 border-forest/25 pl-5"><li><strong className="text-navy">Car travel:</strong> restraint, seating protection and safe containment.</li><li><strong className="text-navy">Portable transport:</strong> carrier formats that match the intended pet size and use.</li><li><strong className="text-navy">Stops and overnight travel:</strong> portable feeding, hygiene and temporary-use accessories.</li><li><strong className="text-navy">Outdoor movement:</strong> light, packable products that are easy to carry and explain at retail.</li></ul></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">3. Compare products by function, construction and customer handling</h2><p className="mt-5">Images can show silhouette and colour but do not confirm construction. Ask what the customer must be able to do with the product: carry it, secure it, open it, clean it, store it and pack it away. Then turn each action into a sample-check question.</p><p className="mt-5">For portable transport, consider a <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/products/travel-car/portable-pet-carrier-backpack">Portable Pet Carrier Backpack</Link> in relation to opening access, mesh coverage, carrying comfort, base support and folded storage. The right format depends on the pet size and the use case you intend to sell—not on a generic claim that one carrier suits every trip.</p><h3 className="mt-9 text-2xl font-semibold tracking-tight text-navy">Use a simple comparison sheet</h3><p className="mt-4">For every shortlisted SKU, record the intended pet size, key material, dimensions, finish, user action, likely retail benefit, packaging requirement and sample observations. The same sheet should capture logo position, colour direction and whether the item is being evaluated as stock supply, private label or a product adjustment.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">4. Ask material questions that match the application</h2><p className="mt-5">Material selection should follow use. A product used near a vehicle may need a different balance of surface feel, cleanability and hardware than a lightweight hiking accessory. Ask for the material specification that applies to the particular sample rather than treating a product name, photo or colour as a complete specification.</p><p className="mt-5">For soft travel products, review fabric weight or construction where available, mesh placement, stitching, zipper operation, reinforcement points, lining and base structure. For tethering or restraint products, review webbing, adjustment range, connection hardware and the intended attachment method. A <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/products/travel-car/dual-use-pet-car-seat-tether">Dual-Use Pet Car Seat Tether</Link>, for instance, should be assessed as part of an in-car use scenario, including the buyer’s own market and customer instructions.</p></section>
        <ArticleCta />
        <section><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">5. Treat samples as a decision stage</h2><p className="mt-5">A sample request is most useful when it has a purpose. Decide whether you need a stock sample to review construction, a branded sample to confirm logo treatment, or a revised development sample to assess a proposed change. State this clearly in the request so the response can match your actual next decision.</p><p className="mt-5">When the sample arrives, test the product against the brief rather than relying on first impressions. Check dimensions, user access, closures, adjustment, finishing, labels and packing. Keep a photo record of the approved reference and list any changes in writing before bulk production discussion begins.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">6. Plan packaging and product information early</h2><p className="mt-5">Packaging affects more than shelf appearance. It can influence protection, carton planning, barcode placement, retail communication and fulfilment preparation. Define whether you need a hangtag, colour box, insert, barcode label, carton marks or a marketplace-specific pack-out before you request a final quote.</p><p className="mt-5">Keep market-facing statements accurate. If labels, care instructions, language requirements or product documentation apply to your channel, provide them as part of the buying brief. This avoids trying to add important packaging decisions after a sample or artwork is already approved.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">7. Evaluate travel and car accessories as a connected system</h2><p className="mt-5">Some products are best sold as standalone items; others are more compelling when they help complete a travel setup. A customer considering a car-trip assortment may pair a restraint with a guard or containment solution. The <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/products/travel-car/dog-car-window-safety-guard">Dog Car Window Safety Guard</Link> can be considered alongside the appropriate car-use accessories, with product suitability and customer instructions reviewed for the specific market.</p><p className="mt-5">For extended journeys with cats, a <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/products/travel-car/foldable-travel-cat-litter-box">Foldable Travel Cat Litter Box</Link> can add a practical hygiene category to a travel range. Its value proposition is easier to communicate when the buyer has already defined storage expectations, cleaning routine and pack-away requirements.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">8. Qualify a supplier with clear, project-specific questions</h2><p className="mt-5">The strongest supplier conversation is specific. Share the product reference, destination market, expected quantity, target timeline, branding requirement and packaging direction. Then ask for the information needed to make a decision: available options, sample route, product-specific MOQ, production timing, packaging choices and any documentation that is relevant to the product and market.</p><p className="mt-5">Avoid treating a marketplace listing or generic catalog description as a final specification. A wholesale program needs an approved product reference, written requirements and a quote that reflects the actual configuration. That protects both the buyer and the supplier from misunderstandings later in the process.</p></section>
        <section className="mt-14"><h2 className="text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">9. Use your RFQ to move from interest to a useful response</h2><p className="mt-5">A useful RFQ gives the supplier enough context to respond thoughtfully while keeping the first contact simple. Include your name, business email, product interests, intended market, approximate quantity or program stage, and any logo, colour, packaging or product-adjustment request. If some details are still open, say so directly.</p><p className="mt-5">When you are ready, send your brief through the <Link className="font-semibold text-forest underline decoration-forest/35 underline-offset-4 hover:text-navy" href="/rfq?intent=wholesale-buying-guide&source=pet-travel-accessories-guide">TROVANE RFQ form</Link>. The goal is a project-relevant discussion—not an assumption about price, stock, certification or delivery before the product and program have been reviewed.</p></section>
        <section className="mt-14 border-t border-navy/15 pt-12"><p className="text-xs font-bold uppercase tracking-[0.16em] text-forest">FAQ</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-navy sm:text-4xl">Questions wholesale buyers commonly ask</h2><div className="mt-8 space-y-9"><div><h3 className="text-2xl font-semibold tracking-tight text-navy">What should be included in a first pet travel accessories inquiry?</h3><p className="mt-3">Start with the products you are considering, your business email, market, approximate quantity or stage, and any customization needs. Add reference images or target requirements if you have them. The supplier can then clarify product-specific MOQ, samples and timing.</p></div><div><h3 className="text-2xl font-semibold tracking-tight text-navy">Should a buyer request samples before discussing branding?</h3><p className="mt-3">Not always. A stock sample may be appropriate for an initial construction review, while a branded or revised sample may be needed to confirm a logo, colour or packaging decision. State the purpose of the sample so the request matches the next decision you need to make.</p></div><div><h3 className="text-2xl font-semibold tracking-tight text-navy">How can a retailer avoid an unfocused travel assortment?</h3><p className="mt-3">Choose a clear travel moment and target customer first. Then select products that support that use case, make sense together at retail and can be explained with accurate benefits and product information.</p></div><div><h3 className="text-2xl font-semibold tracking-tight text-navy">What is the most important supplier-selection criterion?</h3><p className="mt-3">There is no single universal criterion. Look for a supplier conversation that is specific about the product, sample, configuration, packaging and project requirements instead of relying on broad promises that are not tied to your program.</p></div></div></section>
        <div className="mt-14 border-t border-navy/15 pt-8"><Link className="inline-flex items-center text-sm font-bold uppercase tracking-[0.08em] text-forest transition hover:text-navy" href="/blog">← Back to Blog</Link></div>
      </div></div></div>
    </article><section className="border-t border-navy/10 bg-mist px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-[780px] flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-forest">Wholesale sourcing support</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Discuss your pet travel product brief.</h2></div><Link className={`${trovaneButton.primary} shrink-0`} href="/rfq?intent=wholesale-buying-guide&source=pet-travel-accessories-guide-bottom">Request a Quote</Link></div></section><SiteFooter />
  </main>;
}
